CREATE TABLE usuario
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome              VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    email_verificacao BOOLEAN,
    hash_senha        VARCHAR(255)                            NOT NULL,
    cpf               VARCHAR(11)                             NOT NULL,
    ativo             BOOLEAN                                 NOT NULL,
    ultimo_login      TIMESTAMP WITHOUT TIME ZONE,
    criado_em         TIMESTAMP WITHOUT TIME ZONE,
    atualizado_em     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uk_usuarios_email_cpf UNIQUE (email, cpf);

CREATE INDEX idx_usuarios_ativo ON usuario (ativo);

CREATE INDEX idx_usuarios_email ON usuario (email);